name: todo_desktop
description: "Windows Todo App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1

  # Native
  window_manager_plus: ^1.0.5 
  velopack_flutter: ^0.1.0

  # Util
  talker_riverpod_logger: ^4.8.0
  path: ^1.9.1
  path_provider: ^2.1.5

  # Widget
  flutter_svg: ^2.1.0
  flutter_quill: ^11.4.1

  # Model
  freezed_annotation: ^3.0.0 
  json_annotation: ^4.9.0

  # DB
  sembast: ^3.8.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build
  build_runner: ^2.4.15 
  
  # Lint
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5 

  # State
  riverpod_generator: ^2.6.5 

  # Util
  flutter_launcher_icons: ^0.14.3

  # Model
  freezed: ^3.0.6 
  json_serializable: ^6.9.5 

flutter:
  uses-material-design: true

  assets:
    - asset/icon.ico
    - asset/svg/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: asset/font/NotoSansKR-Medium.ttf
          weight: 500